# YAML build definition for this app
# This file is needed only when you want to model your build definitions using YAML
steps:
- script: npm install
- task: Gulp@0
  inputs:
    publishJUnitResults: true
- task: ArchiveFiles@1
  inputs:
    rootFolder: $(Build.SourceDirectory)
    archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    ArtifactName: drop
    ArtifactType: Container
