# YAML build definition for this app
# This file is needed only when you want to model your build definitions using YAML
steps:
- script: npm install
- task: Gulp@0
  inputs:
    publishJUnitResults: true
